// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsoYkK-OYDlHYXqNCiCzMBTRHA7QxMUbo',
    appId: '1:453136945543:web:8ed39eca34c070ff634322',
    messagingSenderId: '453136945543',
    projectId: 'staysyncbase',
    authDomain: 'staysyncbase.firebaseapp.com',
    storageBucket: 'staysyncbase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKRIlFMG-BEyzspJy6C-i-h96BtQYFjoI',
    appId: '1:453136945543:android:8e45e37f7c0ac86a634322',
    messagingSenderId: '453136945543',
    projectId: 'staysyncbase',
    storageBucket: 'staysyncbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnXS0E3lqQ6ljDPLQPIo2OZmyJVX0al50',
    appId: '1:453136945543:ios:b9d65f57f3566779634322',
    messagingSenderId: '453136945543',
    projectId: 'staysyncbase',
    storageBucket: 'staysyncbase.firebasestorage.app',
    iosBundleId: 'com.example.staysyncMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnXS0E3lqQ6ljDPLQPIo2OZmyJVX0al50',
    appId: '1:453136945543:ios:b9d65f57f3566779634322',
    messagingSenderId: '453136945543',
    projectId: 'staysyncbase',
    storageBucket: 'staysyncbase.firebasestorage.app',
    iosBundleId: 'com.example.staysyncMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsoYkK-OYDlHYXqNCiCzMBTRHA7QxMUbo',
    appId: '1:453136945543:web:a4c4ee8e984d969a634322',
    messagingSenderId: '453136945543',
    projectId: 'staysyncbase',
    authDomain: 'staysyncbase.firebaseapp.com',
    storageBucket: 'staysyncbase.firebasestorage.app',
  );
}
